FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /app/

RUN mkdir -p /data

ENV PYTHONPATH=/app
ENV KAFKA_BROKER=kafka:9092

CMD ["python", "log-gen.py", "--kafka-broker", "kafka:9092"]